### PR TITLE
update project dependencies

### PR DESCRIPTION
**Pull request by xurror**

### CODE REVIEW

**Comment by aasaru** [comment]
@xurror the build is failing. Could you first make PR to
https://github.com/apache/fineract-cn-postgresql/tree/spring_boot_2
(I now created the spring_boot_2 branch there).

BTW, I'm working on arranging so you could directly push code to any branch https://github.com/apache/fineract-cn-*/tree/spring_boot_2
(so any branch except develop).
Bear with me - I expect it will be possible in a week.

**Comment by xurror** [comment]
Yeah. Will need to update other libraries on which this dependent for it to pass.
Once I'm done with what is required, I'll let you know

**Comment by xurror** [comment]
@aasaru, this passes now

**Comment by aasaru** [comment]
> @aasaru, this passes now

Excellent work!

**Comment by xurror** [comment]
Thanks, I'll move on to the remaining services

**Pull request merged**
