### PR TITLE
Document APIs for transaction types, journal entries, accounts and le…

### PR DESCRIPTION
**Pull request by Izakey**
Document APIs for transaction types, journal entries, accounts and ledgers

### CODE REVIEW

**Comment by Izakey** [comment]
Hey Awasum, I've updated the PR with some fixes. I await your review.

**Comment by awasum** [comment]
@Izakey Is there a reason for not documenting Chart of accounts and the other accounting reports APIs?

**Comment by awasum** [comment]
In LedgerAPIDoc.documentAddSubLedger():

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is ServiceException{serviceError=ServiceError{code=404, message='Parent ledger 6200 not found.'}}

Is this normal behavior or is it just on my side?

**Comment by Izakey** [comment]
Thanks for the kind review @awasum. Let check if this is from my side and fix it.

**Comment by Izakey** [comment]
Thanks Awasum. I've open a PR https://github.com/apache/fineract-cn-accounting/pull/8 which addresses these accounting reports. Hopefully, this works.

**Pull request merged**
